---
apiVersion: v1
kind: Service
metadata:
  name: projectwiki-bardin-haus-app
  labels:
    ttl: '16'
spec:
  type: NodePort
  ports:
  - nodePort: 32272
    port: 8080
    protocol: TCP
  selector:
    name: projectwiki
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: projectwiki-bardin-haus-vhost
  labels:
    ttl: '16'
spec:
  rules:
  - host: projectwiki.bardin.haus
    http:
      paths:
      - backend:
          serviceName: projectwiki-bardin-haus-app
          servicePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectwiki
  labels:
    ttl: '16'
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      name: projectwiki
  template:
    metadata:
      labels:
        name: projectwiki
        ttl: '16'
    spec:
      volumes:
      - name: run
        emptyDir: {}
      containers:
      - name: projectwiki-bardin-haus-app
        image: projectwiki:latest
        imagePullPolicy: IfNotPresent
        volumeMounts: 
        - mountPath: /var/run/apache2
          name: run
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 200Mi
            cpu: 50m
          requests:
            memory: 100Mi
            cpu: 10m
        command:
        - "apache2"
        - "-D"
        - "FOREGROUND"
        env: &1
        - name: APP_ENV
          value: production
